### ISSUE TITLE
Can't get out of navigation screen when generating wallet manually

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#101]
Building on top of #100 the solution for that issue is to manually create a wallet.
However, when you do that, you can't exist the below screen.
To replicate:
1. #100 
2. To address #100 try to go to settings, on-chain,
3. Generate a wallet
4. Try to click on navigation to exit the view
5. You can't , refresh doesn't work either
6. No logs in server, app .

![Screenshot 2024-09-25 at 11 12 42](https://github.com/user-attachments/assets/1617ee79-622b-4998-b134-252f63e0bfcb)

Console

![Screenshot 2024-09-25 at 11 10 56](https://github.com/user-attachments/assets/3f3852ae-ad45-4514-8db2-a44ae4b37ac1)

```
[Info] [2024-09-25T09:05:44.536Z] Information: Normalizing '_blazor' to 'https://localhost:7016/_blazor'. (blazor.server.js, line 1)
[Info] [2024-09-25T09:05:44.621Z] Information: WebSocket connected to wss://localhost:7016/_blazor?id=Brl27za9HAWBVZwis3wZVQ. (blazor.server.js, line 1)
[Debug] Event listener added: – "#ScanQrCodeModal_show.bs.modal_OnShow" (global.js, line 42)
[Debug] Event listener added: – "#ScanQrCodeModal_hide.bs.modal_OnHide" (global.js, line 42)
[Debug] Event listener removed: – "#ScanQrCodeModal_show.bs.modal_OnShow" (global.js, line 51)
[Debug] Event listener removed: – "#ScanQrCodeModal_hide.bs.modal_OnHide" (global.js, line 51)
[Debug] Event listener added: – "#ScanQrCodeModal_show.bs.modal_OnShow" (global.js, line 42)
[Debug] Event listener added: – "#ScanQrCodeModal_hide.bs.modal_OnHide" (global.js, line 42)
[Debug] Event listener removed: – "#ScanQrCodeModal_show.bs.modal_OnShow" (global.js, line 51)
[Debug] Event listener removed: – "#ScanQrCodeModal_hide.bs.modal_OnHide" (global.js, line 51)
```

**Comment by dennisreimann** [comment]
Now that #100 is also fixed, one can reproduce the state required for testing the fix by commenting out the `await onChainWalletManager.Generate();` in `StateMiddleware`.

I've discusses this issue with @Kukks and even though the quickfix in 31d855465f6d9b4eb475cfdab7ca52d923e8fa29 works, I think this needs to be properly investigated, because some part of the LN node initialization state machine code doesn't seem to be right.
