### ISSUE TITLE
Use retail mode by default for checkout

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#109]
Currently we display pay in wallet, etc which in our use-case which is retail doesn't make sense. 

<img width="405" alt="Screenshot 2024-11-22 at 18 10 17" src="https://github.com/user-attachments/assets/44c3b04f-3895-4058-9cad-353c4bec9cf6">

Checkout should default to what we call `in store` mode on the server

<img width="965" alt="Screenshot 2024-11-22 at 18 12 21" src="https://github.com/user-attachments/assets/2552328b-5587-456b-9519-d94a36bf5cd8">
<img width="443" alt="Screenshot 2024-11-22 at 18 12 17" src="https://github.com/user-attachments/assets/f2df367e-0795-4c2d-8a6d-5a4dbe1dc136">

**Comment by dennisreimann** [comment]
I've updated the settings for stores created via the app to reflect this.
