### ISSUE TITLE
Bug in Sales logic with expired invoices

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#110]
It seems there's a weird bug in sales logic on the dashboard. 

Here's a video on how to replicate it cc @dennisreimann 

Also it seems the logic for sales and top items is different?

https://github.com/user-attachments/assets/9c8449f3-3200-476c-af02-82b61e140dcd

**Comment by dennisreimann** [comment]
I cannot reproduce this and I guess there's something more to it than just expired invoices. For me the simple cases work and the data I get to see is the same as on the server dashboard.

![grafik](https://github.com/user-attachments/assets/c4004bcc-3a3c-43fd-b67d-185eea4a846b)

**Comment by dennisreimann** [comment]
Ok, got it, the Sales bar chart has the wrong number of total sales when there are invoices with multiple manual keypad amounts. Will fix it :)
