### ISSUE TITLE
Position of the `Send` view

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#112]
This is something I am logging so we could bring it up on a design call.

Personally I am still not quite convinced on the positioning and visibility of the `Send` which becomes important CTA for merchants.

Would be good if we could come up with few alternative mocks. We could start with one displaying the button more prominently (see Strike example) and then also consider moving it to navigation.

![Screenshot 2024-11-25 at 13 19 46](https://github.com/user-attachments/assets/d97babf9-6c25-4d02-be8f-20e2849a0d73)

![IMG_7360](https://github.com/user-attachments/assets/18f2bdc4-f8f8-41bd-9b01-94c53c53b470)

**Comment by dstrukt** [comment]
Agree, it needs to be larger, was also designed with Send / Receive being added there originally, but if we move everything to a `Wallet` tab, we can scrap both.

Will explore this path.
