### ISSUE TITLE
Make receipt link in the invoice more prominent

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#113]
An invoice link could be a button/icon. Low priority.
![Screenshot 2024-11-25 at 13 20 40](https://github.com/user-attachments/assets/42c113c1-503c-4b8f-ac8a-24a3c0987dcf)

**Comment by dstrukt** [comment]
It's part of this ticket, and has improved designs I haven't implemented, but agree, it needs to be more prominent!
