### ISSUE TITLE
Add support for account settings

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#13]
- [ ] Add account cell, could utilize the profile picture / user name / role / etc...

<img width="624" alt="Screen Shot 2024-05-24 at 11 39 21 AM" src="https://github.com/btcpayserver/app/assets/6250771/fb92e969-3567-4655-9d2f-d87f68cf263e">

- [ ] Add account settings to detail view
Not 100% sure of everything that should be here, but email address, and password settings changes would be a good start? 
- [ ] And now all the profile picture/name/username info as well
<img width="307" alt="Screen Shot 2024-05-24 at 2 38 21 PM" src="https://github.com/btcpayserver/app/assets/6250771/d24b4323-5f42-4305-9713-6ccdbdd716af">

**Comment by dennisreimann** [comment]
This is done now :)

Can you test master and close if everything works? @dstrukt @pavlenex
