### ISSUE TITLE
Add Refresh user-data 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#21]
@dennisreimann outlined:
> The app doesn't know about a store being created on the server end. It'll know once we refresh the user data.

> Right now we don't communicate those events between app and server

So this issue is our reminder to eventually start refreshing user data

User data should be refreshed on:

- [x] Notifications
- [x] Invoices
- [ ] Store Creation

Once sufficient:

- [ ] Remove the refresh icons (in the future we could arguably add pull to hard refresh functionality)

**Comment by dstrukt** [comment]
I added checkboxes for the various places where we would refresh user data.
