### ISSUE TITLE
Icon replacements

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#24]
most of the icons look great after the latest migration away from font-awesome and the consistency cleanup, but a few lingering assets need to be updated, documenting here:

- [x] general `back-icon` needs to be scaled down slightly inside of the `24x24px` container to replace the current

**Comment by dstrukt** [comment]
Hmm, it looks like it was replace? but I think I'm still seeing the same issue

Both have a bounding box of 24px, can see the scale of each.

<img width="136" alt="Screen Shot 2024-06-28 at 12 37 46 PM" src="https://github.com/btcpayserver/app/assets/6250771/01dc7ae1-9bb0-41bc-9c97-c67caa1bc27a">
<img width="89" alt="Screen Shot 2024-06-28 at 12 40 35 PM" src="https://github.com/btcpayserver/app/assets/6250771/c6d94cf1-c2c5-4e21-b0f9-133dcfff625c">

**Comment by dennisreimann** [comment]
Yes, sorry, my bad. We had to embed the icon sprites directly and I didn't replace the inlined icon sprites when I added the icon. Thanks for the pointer!

**Comment by dstrukt** [comment]
Yeah, your latest caught it - all good!
