### ISSUE TITLE
Implement account switch modal

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#3]
We're using the email address currently, and this also assumes we'll eventually have a profile picture and "name" for the user, which I think in time would be nice to add more customization and personalization, but some things to consider:

### Account (Dashboard):

<img width="956" alt="Screen Shot 2024-04-19 at 11 59 38 AM" src="https://github.com/btcpayserver/app/assets/6250771/3ad60e9e-fd69-4fb5-9a80-bbae591d7f94">

### Dropdown Selector:
<img width="782" alt="Screen Shot 2024-04-19 at 12 04 57 PM" src="https://github.com/btcpayserver/app/assets/6250771/606a9346-ba16-4197-85f3-bd036f1a550f">

### Combined:
<img width="496" alt="Screen Shot 2024-04-19 at 12 08 43 PM" src="https://github.com/btcpayserver/app/assets/6250771/46b871ac-d502-4128-9e7c-d1841e056a00">

### Various states:
<img width="376" alt="Screen Shot 2024-04-19 at 12 12 30 PM" src="https://github.com/btcpayserver/app/assets/6250771/1fb8f300-8fac-4765-8056-45aadccaef98">

Obviously all of this is subject to change, but hopefully the issue gives us something more concrete to discuss.

**Comment by pavlenex** [comment]
I believe this one is done now @dennisreimann ?

**Comment by dennisreimann** [comment]
Yes, this can be closed.
