### ISSUE TITLE
Implement Invoice Details view

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#33]
We could dump all of the Invoice detail data in this view as it currently works on mobile. The only area of concern might be the CTAS, but I'll help clean it up.

Creating a ticket to track.

<img width="321" alt="Screen Shot 2024-06-10 at 11 20 13 PM" src="https://github.com/btcpayserver/app/assets/6250771/7cc07696-ebe3-41c5-9f5b-877f6349a34d">

**Comment by pavlenex** [comment]
This is a good time to think what's actually useful information and if provided information is easy to understand.
For example 
- ambiguity between invoice and order id in the app context, 
- Created, Expiration, Monitoring, - is it clear what it is?
- Transaction speed, is this really relevant info, it seems very subjective, shouldn't we have transaction fee instead which is a better metric?
- Redirect URL, is it really needed?

We don't have to clean things up entirely now, but let's keep chatting about this, as I am sure improvements here can also be useful for the Server.

<img width="724" alt="Screenshot 2024-06-19 at 13 09 31" src="https://github.com/btcpayserver/app/assets/36959754/b3815f4a-bc40-4704-ad7c-19cc8df4ef20">

**Comment by dstrukt** [comment]
Completely agree @pavlenex, now that we're past the basic data dump, also started to document a few areas where we could clean up or simplify these views, specifically for the App.

**Comment by dstrukt** [comment]
Closing, as this supersedes: https://github.com/btcpayserver/app/issues/53
