### ISSUE TITLE
Creating an account on the app - log in immediately

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#40]
Is there a reason why user cannot immediately log into the app when they create an account, instead we give them `account created` message and they have to log in again?

I would understand situations where email needs to be verified or account confirmed but in this case I don't have those set up.

<img width="511" alt="Screenshot 2024-06-19 at 12 35 05" src="https://github.com/btcpayserver/app/assets/36959754/3d8e7325-220b-4dcc-ae69-719794882193">

@dennisreimann any thoughts?

**Comment by dstrukt** [comment]
Agreed, I think in this instance, if no additional auth or approval necessary, I don't see any reason we shouldn't just dump the user into the next step after account creation.
