### ISSUE TITLE
Add better copy to Create a Store

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#41]
I am sure there's at least something we can do in terms of copy that can explain user what the store is to avoid ambiguity. 

<img width="631" alt="Screenshot 2024-06-19 at 12 38 04" src="https://github.com/btcpayserver/app/assets/36959754/b9599f8a-e656-4bef-a570-b362bf952d12">

**Comment by dstrukt** [comment]
Let's discuss in tomorrow's design call.

**Comment by dstrukt** [comment]
Opted to add the one-line we currently use on a First Store creation.
