### ISSUE TITLE
Move Lightning and wallet settings from the dashboard Getting Started to > Settings

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#44]
Once everything is set up, there's not really a reason to keep these options in the getting started. 
I think we should move them into Settings.

@dstrukt We may need to discuss information architecture here though, since I am not 100% sure how to pack all of these together.

What we expose on the dashboard:
- **Store Settings** (settings/store/) this is already added in the settings. ✅ 
- **Wallet**, which is currently unclear if it should be wallet for sending/receiving funds cc @Kukks do you know. If yes then we should write Wallet into Send/Receive. Ideally unified on and on-chain balance and send/receive.
  - **Wallet Settings**  - can be moved to settings
- Wallet Settings
- Node Settings (Lightning) - can be moved to settings, but I think we can break that page into a few smaller views

<img width="1397" alt="Screenshot 2024-06-19 at 12 47 02" src="https://github.com/btcpayserver/app/assets/36959754/51fa5ce2-3023-4287-9531-c1980677522e">

**Comment by dstrukt** [comment]
Agree it should be moved into Settings. Wasn't being too pushy yet until everything was hooked up sufficiently, but will follow up with some mocks for discussion so we can kill that section, now that we know we're not going to need to utilize it.

**Comment by dstrukt** [comment]
I think for now, let's add options for the Wallet and the Lightning Node in settings, and it mirrors what we have in the Getting Started section, and when we're ready, we can kill it: 

<img width="497" alt="Screen Shot 2024-06-26 at 8 24 15 PM" src="https://github.com/btcpayserver/app/assets/6250771/f02ee163-924f-4596-a356-93c92b362088">

cc @dennisreimann

**Comment by pavlenex** [comment]
@dennisreimann is this one completed?

**Comment by dennisreimann** [comment]
I think so. If there's still something left, we can open up a new issue with specific details.
