### ISSUE TITLE
Revocation of the invite link

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#48]
Kukks pointed out that when a user is invited, there may be a situation where store owner would want to revoke their access (eg, invited by mistake).

Open questions:
- User can just be removed from the store (mentioned by @dennisreimann )
- Don't we have expiration time for invite links?

**Comment by dstrukt** [comment]
conceptual ACK

- If the invite code has been used, but then revoked, we'd just remove the user and log them out on state refresh? 
- I'd think a 24hour to 72hour (for the weekend, employee invited on a friday, working on monday?) expiration for an invite link would work?

**Comment by dennisreimann** [comment]
>  If the invite code has been used, but then revoked, we'd just remove the user and log them out on state refresh?

Nope, once the invitation is accepted it's done and at that point and the user would have to get removed the regular way — same as without any invite.

> I'd think a 24hour to 72hour (for the weekend, employee invited on a friday, working on monday?) expiration for an invite link would work?

We';ve settled on an expiry of seven days and I think that's fine to handle these cases.

**Comment by dstrukt** [comment]
Ahh I see, it's not a persistent invite, but a one-and-done. 

All sounds good, just making sure I understand the mechanics for testing!

**Comment by dstrukt** [comment]
Agreed.

Side thought - would it make sense to simply call the CTA `Cancel` in the Pending Invite case? Does the same thing (removal), but different CTA label?

**Comment by dennisreimann** [comment]
There is no canceling of the invitation at that point, because that would basically mean to remove the user as well (they could not register or sign in, so it doesn't make much sense to keep the user record).
