### ISSUE TITLE
Click on Recent Transaction on Keypad leads to an iFrame error

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#58]
Should resolve on an invoice detail I believe.

Hover shows the proper URL with the `invoices/{invoiceID}`, but clicking on it keeps/resolves to the `/pos` URL, and the error below.

Might be a known issue, but tracking regardless.

<img width="689" alt="Screen Shot 2024-06-28 at 12 35 33 PM" src="https://github.com/btcpayserver/app/assets/6250771/3cfa3a29-1273-4833-9d38-4f2af6e66a19">

**Comment by pavlenex** [comment]
I think we resolved this one now.
