### ISSUE TITLE
Clean up Lightning Node view

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#59]
Currently:
<img width="1365" alt="Screen Shot 2024-06-28 at 1 51 13 PM" src="https://github.com/btcpayserver/app/assets/6250771/df622d40-de4b-43a4-a4b4-2cb414b6a30c">
<img width="1344" alt="Screen Shot 2024-06-28 at 1 52 45 PM" src="https://github.com/btcpayserver/app/assets/6250771/fae99df1-a62b-4a05-91f0-ce6478faecdf">

**Comment by pavlenex** [comment]
@dstrukt is this one done, or could we be more specific of what needs to be cleaned up if not ,the issue is pretty broadly scoped imo.

**Comment by dstrukt** [comment]
I haven't been able to see the view in a bit, as I'm having issues getting this to load, but the UI could use some clean-up and organization.

Would be happy to close if I can view the latest.

**Comment by dstrukt** [comment]
My setup is working again, and I'll try to help clean this.

**Comment by dstrukt** [comment]
Outside of payments or what is now `Withdraw`, I think this is initial goal is completed to format the view a little bit.
