### ISSUE TITLE
Finalize the removal of the Getting Started section from the dashboard 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#66]
As we're moving things into settings, #44 we'll need space for balance chart so we should move remaining of the getting started steps 

- [ ] Move Lightning wallet send and receive into "send and receive views" (this one will need to be discussed in terms of the unified balance)
- [x] Remove the getting started page
- [x] Remove the "keypad created" welcome message

**Comment by dstrukt** [comment]
Small note for this one, the `Getting Started` section *could* be used for reminding the Owner to set up a Passcode, and/or users to configure a Backup. Unless we're going to push this into the onboarding flow at the beginning. 

However, in the current state, agree, it makes sense to at least hide.

**Comment by pavlenex** [comment]
Why is passcode important? Could we use notification or something else? For backup we could prompt once there's fund in the wallet as per BDG https://bitcoin.design/guide/daily-spending-wallet/backup-and-recovery/cloud-backup/

**Comment by dstrukt** [comment]
Going to close this and open a specific issue for Back-ups, as we have an Issue for Send flows specifically as well now.
