### ISSUE TITLE
Can't dismiss the `Store has been created` message, it keeps appearing on refresh

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#75]
As agreed on dev call let's remove these, they don't bring much relevancy to the user as we're setting it all up for them in the background.
<img width="1056" alt="Screenshot 2024-07-29 at 23 50 00" src="https://github.com/user-attachments/assets/7ef104cf-2b81-44da-ac6b-41feccf3b041">

**Comment by pavlenex** [comment]
The only way to dismiss is to click on a different tab for example keypad and then return, weird. Anyway we should kill that msg.

**Comment by dstrukt** [comment]
ACK to killing.
