### ISSUE TITLE
[Bug] Invoice preview on pos not displayed

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#77]
When you have a few invoices, and try to access them through the POS view (quick invoice view), for some reason when you click on the invoice you'll land on a blank page. Console logs say this:

```
[Error] Refused to display 'https://localhost:14142/invoices/SszkSoNhCvZtF7jXnFKgGr' in a frame because it set 'X-Frame-Options' to 'DENY'.
[Error] Failed to load resource: the server responded with a status of 404 () (SszkSoNhCvZtF7jXnFKgGr, line 0)
[Error] Refused to display 'https://localhost:14142/invoices/Xw4hoJdWNz7i71o3i2LdmD' in a frame because it set 'X-Frame-Options' to 'DENY'.
[Error] Failed to load resource: the server responded with a status of 404 () (Xw4hoJdWNz7i71o3i2LdmD, line 0)
```

Preview videeo

https://github.com/user-attachments/assets/585ae32f-d5e4-40cf-870f-566e0d34766c

**Comment by dennisreimann** [comment]
We'll need to disable the access of the recent transactions in that context, because it would lead to accessing the server views in the POS iframe. I'll fix this on the server and we can use the invoices list for accessing that info inside the app.

**Comment by dstrukt** [comment]
Can confirm on my end as well, and would it make more sense to just label it `Recent Invoices`? I still conceptually like Transactions, as I think that's a bit clearer to the end user, but we use Invoices everywhere else, and even on the Dashboard.

**Comment by pavlenex** [comment]
I've read the design note calls but I am not quite convinced this is a solution. This feature was implemented for a `cashier` role aka someone who only has a view only mode on the POS and for them this is a way to double-check if the payment is settled.

@dennisreimann have you guys discussed how this solution may be impacted by other roles?

**Comment by dennisreimann** [comment]
As discussed on Mattermost: For now the invoices list can be an equivalent for roles, whcih are not permitted to access the Dashboard. The recent transactions list feature of the POS requires the `CanViewInvoices` permission, which is also required for the invoices list inside the app.
