### ISSUE TITLE
Server refresh with auth inputs not working

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#86]
Just refreshes, but forced to click Connect to show the auth input fields. A bug AFAIC, unless we changed this flow unknowingly?

https://github.com/user-attachments/assets/f094ea98-0344-4aa5-8c5a-134abcbc8aae

**Comment by dennisreimann** [comment]
This has been like that from the start and I think for the Connect screen it is assumed to work that way.

**Comment by dstrukt** [comment]
In the past, when I've input the Server URL, it updates/refreshes with the Username/Password & Server Brancing? It has been that way since it was essentially implemented, no?

**Comment by dstrukt** [comment]
I'm still convinced I've seen the email/pass + server branding appear on refresh after inputting the Server URL, but @dennisreimann has told me this is not how it has ever worked, so going to close this issue!
