### ISSUE TITLE
Encryption Key input view breaks

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#94]
When there's no QR code, the view is quite broken:

<img width="900" alt="Screen Shot 2024-08-22 at 3 51 12 PM" src="https://github.com/user-attachments/assets/85eaaecd-2849-4016-8e92-32ae14569bc7">

**Comment by dennisreimann** [comment]
Updated both views :)

![grafik](https://github.com/user-attachments/assets/fd65cba6-2315-4c27-aa0b-32066431afd9)


![grafik](https://github.com/user-attachments/assets/69f9718d-fe34-4d18-9405-959e0c3442b2)
